name: Build and Deploy      # on every push to master or pull request, this frontend app will 
                            # rebuild and deploy onto GitHub Pages, hopefully
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and Build 🔧 
        run: |
          npm ci
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages 
          folder: build 
#   build:
#     name: Build
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: ./frontend
        
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3
    
#     - name: Install Node.js
#       uses: actions/setup-node@v3
#       with:
#         node-version: 14
    
#     - name: Install NPM packages
#       run: npm ci                   # based on package-lock.json
    
#     - name: Build project
#       run: npm run build
    
#     - name: Run tests
#       run: npm run test

#     - name: Upload production-ready build files
#       uses: actions/upload-artifact@v2
#       with:
#         name: production-files
#         path: frontend/build               # used to deploy contents in this directory to gh-pages branch
  
#   deploy:
#     name: Deploy
#     needs: build
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/main' # validates current branch is master
    
#     steps:
#     - name: Download artifact
#       uses: actions/download-artifact@v2
#       with:
#         name: production-files
#         path: frontend/build
#     - name: Deploy
#       uses: JamesIves/github-pages-deploy-action@v4
#       with:
#         branch: gh-pages
#         folder: frontend/build

#     - name: Deploy to gh-pages
#       run: npm run deploy
#       working-directory: ./frontend/build
#       uses: peaceiris/actions-gh-pages@v3 # from gh-actions marketplace
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }} # might need to edit permissions here
#         publish_dir: ./frontend/build
#         force_orphan: true
