name: Rust backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always        # displays colored output in terminal

jobs:
  build:
    defaults:
      run:
        working-directory: backend/internal_api
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose